export type CommandRisk = '只读' | '写入结果' | '关键确认' | '高风险维护';

export type CommandEntry = {
  id: string;
  group: string;
  title: string;
  purpose: string;
  command: string;
  risk: CommandRisk;
  output: string;
  note?: string;
};

export const projectRootCommand = 'cd /Users/brucehuang/Documents/CLI_research';

export const commands: CommandEntry[] = [
  {
    id: 'disclosure-audit',
    group: '公开申报',
    title: '运行公开申报命题审计',
    purpose: '只读现有13F、Congress SQLite与本地行情，按公开日后的下一交易日评估命题。',
    command: 'cd /Users/brucehuang/Documents/ChatGPT/crawler && PYTHONPATH=src /Users/brucehuang/Documents/CLI_research/.venv/bin/python -m disclosurelab --compact',
    risk: '写入结果',
    output: 'crawler/reports/disclosure_research.json 与 disclosure_research.md',
    note: '不会联网或更新源数据；只写入小型研究摘要。',
  },
  {
    id: 'congress-status',
    group: '公开申报',
    title: '查看Congress数据覆盖',
    purpose: '查看两院申报、解析状态、交易数量和同步审计，不下载数据。',
    command: 'cd /Users/brucehuang/Documents/ChatGPT/crawler && PYTHONPATH=src .venv/bin/python -m congressinsider status',
    risk: '只读',
    output: '终端JSON覆盖摘要',
  },
  {
    id: 'sec13f-dashboard',
    group: '公开申报',
    title: '打开现有13F仪表盘',
    purpose: '从已生成的本地HTML查看季度、机构和CUSIP信号，不刷新SEC数据。',
    command: 'cd /Users/brucehuang/Documents/ChatGPT/crawler && PYTHONPATH=src .venv/bin/python -m sec13f serve --no-open',
    risk: '只读',
    output: 'http://127.0.0.1:8765/index.html',
    note: '只启动本地静态服务；Ctrl+C停止。',
  },
  {
    id: 'tutorial',
    group: '入门与维护',
    title: '运行离线教程',
    purpose: '用合成数据熟悉完整研究流程，不联网。',
    command: '.venv/bin/python scripts/demo_research.py',
    risk: '写入结果',
    output: 'results/tutorial/<run>/metrics.json',
    note: '合成结果只能学习，不能作为交易证据。',
  },
  {
    id: 'update-data',
    group: '数据管理',
    title: '更新行情数据',
    purpose: '联网更新 A 股、美股或指定股票池的本地行情。',
    command: '.venv/bin/python scripts/update_data.py --market us --universe baseline',
    risk: '写入结果',
    output: 'data/daily/ 与质量摘要',
    note: '会联网并重写本地行情文件，运行后必须检查数据质量。',
  },
  {
    id: 'check-data',
    group: '数据管理',
    title: '检查数据质量',
    purpose: '查看覆盖、缺失、重复时间戳和数据新鲜度。',
    command: '.venv/bin/python scripts/check_data.py --market us --quiet',
    risk: '只读',
    output: 'data/quality_summary.json 与终端摘要',
  },
  {
    id: 'radar-scan',
    group: '每日雷达',
    title: '扫描美股自选池',
    purpose: '按量比、动量和突破规则对固定自选池排序。',
    command: '.venv/bin/quant scan --workspace config/workspace.yaml --market us --profile momentum_volume',
    risk: '写入结果',
    output: 'results/radar/us/<profile>/<date>/scan.json',
    note: '这是描述性排名，不是上涨概率或交易建议。',
  },
  {
    id: 'radar-track',
    group: '每日雷达',
    title: '跟踪雷达信号',
    purpose: '登记信号并更新 1/3/5/10/20 个交易日的后续表现。',
    command: '.venv/bin/quant signals track --workspace config/workspace.yaml --market us --profile momentum_volume',
    risk: '写入结果',
    output: '信号跟踪 JSON',
  },
  {
    id: 'explore-backtest',
    group: '策略研究',
    title: '探索性回测',
    purpose: '在事先限定的训练区间内快速试验单组参数。',
    command: '.venv/bin/python scripts/run_backtest.py --strategy momentum --market us --end 2022-12-30 -p lookback=120 -p top_n=2',
    risk: '写入结果',
    output: 'results/<run>/metrics.json',
    note: '探索结果不能直接获得模拟或实盘准入。',
  },
  {
    id: 'scan-preview',
    group: '策略研究',
    title: '预览正式实验边界',
    purpose: '只预览训练、验证和最终测试日期，不暴露测试成绩。',
    command: '.venv/bin/python scripts/run_parameter_scan.py --strategy momentum --market us --start 2018-01-01 --end 2026-07-20 --study-file momentum_001.json -p lookback=60,120,250 -p top_n=1,2 -p rebalance=20 --walk-forward --preview',
    risk: '只读',
    output: '终端边界预览',
  },
  {
    id: 'scan-run',
    group: '策略研究',
    title: '运行冻结参数扫描',
    purpose: '训练期选参，通过前置验证后仅运行一次最终测试。',
    command: '.venv/bin/python scripts/run_parameter_scan.py --strategy momentum --market us --start 2018-01-01 --end 2026-07-20 --study-file momentum_001.json -p lookback=60,120,250 -p top_n=1,2 -p rebalance=20 --walk-forward --compact',
    risk: '关键确认',
    output: 'ranking.csv、scan.json、metrics.json 与实验记录',
    note: '会消耗最终测试；实验文件不可当作没看过再次使用。',
  },
  {
    id: 'workflow',
    group: '策略研究',
    title: '运行统一研究工作流',
    purpose: '依次执行质量摘要、正式参数扫描和 GPT Quant 验证。',
    command: '.venv/bin/quant workflow --workspace config/workspace.yaml --strategy momentum --market us --universe baseline --membership-file config/universe_history.csv --start 2018-01-01 --end 2026-07-20 --study-file momentum_001.json -p lookback=60,120,250 -p top_n=1,2 -p rebalance=20 --walk-forward',
    risk: '关键确认',
    output: '正式研究结果与 strategy_validation_decision',
    note: '同样可能消耗最终测试，页面必须先显示边界并要求确认。',
  },
  {
    id: 'summarize',
    group: '结果与验证',
    title: '汇总月度结果',
    purpose: '把指定月份的研究结果整理为统一摘要。',
    command: '.venv/bin/python scripts/summarize_results.py --month 2026-08',
    risk: '写入结果',
    output: 'results/summary.csv',
  },
  {
    id: 'validate',
    group: '结果与验证',
    title: '验证研究证据',
    purpose: '检查协议、执行模型、样本、稳健性和模拟盘准入条件。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli validate-cli-result /absolute/path/to/metrics.json',
    risk: '只读',
    output: 'strategy_validation_decision JSON',
    note: 'BLOCKED 代表证据不足或口径不合格，不代表程序故障。',
  },
  {
    id: 'paper-signal',
    group: '模拟账户',
    title: '生成模拟调仓信号',
    purpose: '从已验证的 metrics.json 生成确定性、可重放校验的目标信号。',
    command: '.venv/bin/python scripts/generate_paper_signal.py /absolute/path/to/metrics.json --output /absolute/path/to/paper-signal.json',
    risk: '写入结果',
    output: 'paper-signal.json',
  },
  {
    id: 'paper-init',
    group: '模拟账户',
    title: '初始化模拟账户',
    purpose: '以指定现金创建绑定研究证据的本地模拟账本。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli paper-init /absolute/path/to/metrics.json /absolute/path/to/paper-state.json --cash 100000',
    risk: '写入结果',
    output: 'paper-state.json',
  },
  {
    id: 'paper-mark',
    group: '模拟账户',
    title: '更新模拟账户估值',
    purpose: '用指定交易日的价格更新持仓市值和账户状态。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli paper-mark /absolute/path/to/paper-state.json --date 2026-08-30 --price AAPL=230.5',
    risk: '写入结果',
    output: '更新后的 paper-state.json',
  },
  {
    id: 'paper-order',
    group: '模拟账户',
    title: '记录模拟订单',
    purpose: '按明确的方向、数量、成交价和价格时点写入模拟成交。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli paper-order /absolute/path/to/paper-state.json --timestamp 2026-08-31T09:35:00-04:00 --symbol AAPL --side BUY --quantity 10 --price 230.5 --price-as-of 2026-08-31T09:35:00-04:00',
    risk: '关键确认',
    output: '更新后的 paper-state.json 与审计记录',
  },
  {
    id: 'paper-rebalance',
    group: '模拟账户',
    title: '执行模拟调仓',
    purpose: '使用新鲜价格把模拟账户调整到目标信号。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli paper-rebalance /absolute/path/to/paper-state.json /absolute/path/to/paper-signal.json --execution-at 2026-08-31T09:35:00-04:00 --price-as-of 2026-08-31T09:35:00-04:00 --price AAPL=230.5',
    risk: '关键确认',
    output: '模拟成交与更新后的账本',
    note: '信号重放、陈旧价格或证据变化都会被拒绝。',
  },
  {
    id: 'paper-report',
    group: '模拟账户',
    title: '查看模拟账户报告',
    purpose: '只读查看现金、持仓、净值、交易和当前状态。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli paper-report /absolute/path/to/paper-state.json',
    risk: '只读',
    output: '模拟账户 JSON 报告',
  },
  {
    id: 'paper-revoke',
    group: '模拟账户',
    title: '撤销模拟账户授权',
    purpose: '因证据失效或人工决定使账户停止继续执行。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli paper-revoke /absolute/path/to/paper-state.json --reason "evidence changed"',
    risk: '关键确认',
    output: 'HALTED 状态与撤销原因',
  },
  {
    id: 'risk-preflight',
    group: '风险控制',
    title: '风险控制预检',
    purpose: '不连接 TWS，仅检查本机配置、状态目录和依赖是否就绪。',
    command: '.venv/bin/python scripts/run_live_risk.py --config config/live_risk.paper.yaml --preflight',
    risk: '只读',
    output: '本地 readiness 报告',
  },
  {
    id: 'risk-once',
    group: '风险控制',
    title: '读取一次账户风险快照',
    purpose: '连接已配置的 TWS/IB Gateway 并评估风险状态。',
    command: '.venv/bin/python scripts/run_live_risk.py --config config/live_risk.paper.yaml --once',
    risk: '关键确认',
    output: 'NORMAL / FREEZE / REDUCE / LIQUIDATE 状态与审计',
    note: '可能触发撤单或风险处置；必须先通过 preflight 并人工确认。',
  },
  {
    id: 'risk-simulate',
    group: '风险控制',
    title: '运行风险状态机模拟',
    purpose: '用内置假数据演示 NORMAL 到 LIQUIDATE 的状态变化。',
    command: '.venv/bin/python scripts/simulate_live_risk.py',
    risk: '只读',
    output: '模拟观测、撤单与订单 JSON',
  },
  {
    id: 'event-study',
    group: '专项分析',
    title: '股票事件研究',
    purpose: '比较事件日前后个股、基准和同行的表现。',
    command: '.venv/bin/python scripts/analyze_stock_event.py --symbol AAPL --benchmark SPY --event-date 2026-07-30',
    risk: '写入结果',
    output: '事件研究 metrics.json',
  },
  {
    id: 'brand-score',
    group: '专项分析',
    title: '品牌复利公司评分',
    purpose: '按品牌、增长、需求、扩张、盈利质量和估值进行结构化评分。',
    command: '.venv/bin/python scripts/score_brand_compounders.py --input config/brand_compounders.json --compact',
    risk: '写入结果',
    output: '品牌复利研究结果',
  },
  {
    id: 'asset-growth',
    group: '专项分析',
    title: '资产增长复盘',
    purpose: '读取资产流水，比较当前进度与目标。',
    command: '.venv/bin/python scripts/review_asset_growth.py config/asset_ledger.csv --target 1000000',
    risk: '写入结果',
    output: '资产增长复盘报告',
  },
  {
    id: 'agent-demo',
    group: '入门与维护',
    title: '运行 Agent 演示',
    purpose: '不使用 API Key，演示工具调用、数据反馈和审计循环。',
    command: 'PYTHONPATH=../gpt_quant/src .venv/bin/python -m gpt_quant.cli agent-demo',
    risk: '只读',
    output: 'Agent 工具调用与审计摘要',
  },
  {
    id: 'tests',
    group: '入门与维护',
    title: '运行测试',
    purpose: '验证研究、风控和模拟交易逻辑。',
    command: '.venv/bin/python -m pytest -q',
    risk: '只读',
    output: 'pytest 测试结果',
  },
  {
    id: 'normalize',
    group: '入门与维护',
    title: '迁移旧行情格式',
    purpose: '重写全部旧日线文件，统一成交量单位和来源字段。',
    command: '.venv/bin/python scripts/normalize_data.py',
    risk: '高风险维护',
    output: '重写 data/daily 下的 Parquet 文件',
    note: '没有 --help 或 dry-run；必须备份数据后由维护者手动执行，普通页面不提供运行按钮。',
  },
];

export const commandGroups = [...new Set(commands.map((command) => command.group))];
